language: node_js

node_js: 6

branches:
  only:
    - master

cache:
  directories:
    - node_modules

script:
  - npm test

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - npm install firebase-tools@3.5.0 -g
  - npm run build

deploy:
  provider: firebase
  token: $FIREBASE_TOKEN
