language: node_js

node_js: 6

branches:
  only:
    - master

cache:
  directories:
    - node_modules

script:
  - npm test

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: script
  script: deploy.sh
  on:
    branch: master
