export enum Actions {
  ADD_ROOM = <any>'ADD_ROOM',
  SELECT_ROOM = <any>'SELECT_ROOM',
  ADD_SUPPLY = <any>'ADD_SUPPLY',
  SUPPLY_REQUESTED = <any>'SUPPLY_REQUESTED',
  SHOW_FEEDBACK_FORM = <any>'SHOW_FEEDBACK_FORM',
  SHOW_REQUESTED_SUPPLY = <any>'SHOW_REQUESTED_SUPPLY',
  HIDE_REQUESTED_SUPPLY = <any>'HIDE_REQUESTED_SUPPLY'
}
